import { db } from "./db";
import { meetings, events, literature, servicePositions } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const existingMeetings = await db.select().from(meetings);
  if (existingMeetings.length > 0) return;

  await db.insert(meetings).values([
    { name: "Morning Meditation", dayOfWeek: "Monday", startTime: "7:00 AM", endTime: "8:00 AM", meetingType: "Open", format: "Meditation & Sharing", location: "Another Chance Group", description: "Start your week with a guided meditation and open sharing." },
    { name: "Step Study", dayOfWeek: "Monday", startTime: "7:00 PM", endTime: "8:30 PM", meetingType: "Closed", format: "Step Study", location: "Another Chance Group", description: "In-depth study of the 12 Steps of NA." },
    { name: "Open Discussion", dayOfWeek: "Tuesday", startTime: "7:00 PM", endTime: "8:30 PM", meetingType: "Open", format: "Topic Discussion", location: "Another Chance Group", description: "Open topic discussion meeting. All are welcome." },
    { name: "Literature Study", dayOfWeek: "Wednesday", startTime: "7:00 PM", endTime: "8:30 PM", meetingType: "Closed", format: "Literature Study", location: "Another Chance Group", description: "Reading and discussing NA literature together." },
    { name: "Traditions Workshop", dayOfWeek: "Thursday", startTime: "6:30 PM", endTime: "7:30 PM", meetingType: "Open", format: "Workshop", location: "Another Chance Group", description: "Study and discuss the 12 Traditions of NA." },
    { name: "Living Clean", dayOfWeek: "Thursday", startTime: "8:00 PM", endTime: "9:00 PM", meetingType: "Closed", format: "Topic Discussion", location: "Another Chance Group", description: "Discussion focused on living clean in everyday life." },
    { name: "Speaker Meeting", dayOfWeek: "Friday", startTime: "8:00 PM", endTime: "9:30 PM", meetingType: "Speaker", format: "Speaker", location: "Another Chance Group", description: "Guest speaker shares their experience, strength, and hope." },
    { name: "Just for Today", dayOfWeek: "Saturday", startTime: "10:00 AM", endTime: "11:00 AM", meetingType: "Open", format: "Daily Reading", location: "Another Chance Group", description: "Reading from 'Just for Today' followed by open sharing." },
    { name: "Candlelight Meeting", dayOfWeek: "Saturday", startTime: "8:00 PM", endTime: "9:30 PM", meetingType: "Open", format: "Candlelight", location: "Another Chance Group", description: "A reflective candlelight meeting with open sharing." },
    { name: "Gratitude Meeting", dayOfWeek: "Sunday", startTime: "6:00 PM", endTime: "7:30 PM", meetingType: "Open", format: "Gratitude Sharing", location: "Another Chance Group", description: "End the week with gratitude sharing and fellowship." },
  ]);

  await db.insert(events).values([
    { title: "Monthly Birthday Celebration", description: "Celebrate members' recovery anniversaries with cake, fellowship, and sharing. All members and their families are welcome.", eventDate: "2026-03-14", eventTime: "7:00 PM", endTime: "9:00 PM", location: "Another Chance Group", eventType: "celebration" },
    { title: "Spring Cleanup Day", description: "Help keep our meeting space clean and welcoming. Bring cleaning supplies if you have them. Lunch will be provided.", eventDate: "2026-03-21", eventTime: "9:00 AM", endTime: "2:00 PM", location: "Another Chance Group", eventType: "service" },
    { title: "Chairperson's Workshop", description: "Learn how to effectively chair an NA meeting. This workshop covers meeting formats, handling disruptions, and sharing your story. Required for new chairpersons.", eventDate: "2026-04-05", eventTime: "2:00 PM", endTime: "4:00 PM", location: "Another Chance Group", eventType: "workshop" },
    { title: "Area Convention 2026", description: "Annual area convention featuring speakers, workshops, and fellowship activities. Registration required. See GSR for details.", eventDate: "2026-05-15", eventTime: "9:00 AM", endTime: "10:00 PM", location: "Convention Center - 123 Main St", eventType: "area" },
    { title: "Game Night & Fellowship", description: "Come enjoy a night of games, food, and clean fun with your fellow recovering addicts. Bring a dish to share!", eventDate: "2026-04-18", eventTime: "6:00 PM", endTime: "10:00 PM", location: "Another Chance Group", eventType: "celebration" },
    { title: "Guidelines Workshop", description: "The Peacekeeper will hold a workshop covering the Another Chance Group Guidelines for all trusted servants.", eventDate: "2026-03-28", eventTime: "1:00 PM", endTime: "3:00 PM", location: "Another Chance Group", eventType: "workshop" },
  ]);

  await db.insert(literature).values([
    { title: "Basic Text - Narcotics Anonymous", description: "The foundational text of NA. It contains the NA philosophy, the Twelve Steps and Twelve Traditions, and personal stories of recovery from addicts.", category: "Books", externalUrl: "/literature/basic-text.pdf" },
    { title: "Just for Today", description: "Daily meditations for recovering addicts. Each day includes a quote, a meditation, and a thought for the day to guide your recovery journey.", category: "Daily Readings", externalUrl: "https://www.na.org/products/literature" },
    { title: "It Works: How and Why", description: "An in-depth exploration of the Twelve Steps and Twelve Traditions of NA, explaining how and why they work in the recovery process.", category: "Books", externalUrl: "/literature/it-works-how-and-why.pdf" },
    { title: "Living Clean: The Journey Continues", description: "Addresses the challenges that members face in ongoing recovery, including relationships, loss, spirituality, and daily living.", category: "Books", externalUrl: "https://www.na.org/products/literature" },
    { title: "The NA Step Working Guides", description: "A companion workbook to help members work through the Twelve Steps with their sponsor. Contains questions and exercises for each step.", category: "Booklets", externalUrl: "/literature/step-working-guides.pdf" },
    { title: "IP #7: Am I an Addict?", description: "An informational pamphlet designed for the still-suffering addict who may be questioning whether they have a drug problem.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3107-IP-7-English.pdf" },
    { title: "IP #22: Welcome to Narcotics Anonymous", description: "A brief introduction to the Narcotics Anonymous program for newcomers, explaining what NA is and how it works.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3122_Welcome-IP-22-English.pdf" },
    { title: "IP #29: An Introduction to NA Meetings", description: "Explains the different types of NA meetings and what to expect when attending your first meeting.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3129-IP-29-English.pdf" },
    { title: "IP #11: Sponsorship", description: "Explains the role of a sponsor in NA recovery and how to find and work with a sponsor effectively.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3111_Sponsorship-IP-11-English.pdf" },
    { title: "Group Trusted Servant Guide", description: "A handbook for trusted servants at the group level, covering roles, responsibilities, and best practices for service.", category: "Service Material", externalUrl: "https://www.na.org/products/literature" },
    { title: "The Group Booklet", description: "Guidelines and suggestions for NA groups on how to operate effectively while staying true to NA principles.", category: "Service Material", externalUrl: "https://www.na.org/products/literature" },
    { title: "Key Tags & Medallions", description: "Recovery milestones are celebrated with key tags for various lengths of clean time: White (Surrender), Orange (30 days), Green (60 days), Red (90 days), Blue (6 months), Yellow (9 months), Glow-in-dark (1 year), and more.", category: "Key Tags & Medallions" },
    { title: "IP #1: Who, What, How and Why", description: "Introduces the basics of the NA program, including who is an addict, what NA is, how the program works, and why it works.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3101-IP-1-English.pdf" },
    { title: "IP #2: The Group", description: "Describes the purpose and function of NA groups, how they operate, and how members participate.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3102-IP-2-English.pdf" },
    { title: "IP #5: Another Look", description: "Encourages addicts who have relapsed or are struggling to take another look at the NA program.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3105_Another-Look-IP-5-English.pdf" },
    { title: "IP #6: Recovery and Relapse", description: "Discusses the nature of relapse and how addicts can use the NA program to find recovery.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3106_Recovery-Relapse-IP-6-English.pdf" },
    { title: "IP #8: Just for Today", description: "Focuses on living in the moment and applying the NA program one day at a time.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3108_Just-for-Today-IP-8-English.pdf" },
    { title: "IP #9: Living the Program", description: "Shares experience about applying NA principles in everyday life and maintaining recovery.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3109-IP-9-English.pdf" },
    { title: "IP #12: The Triangle of Self-Obsession", description: "Explores the three sides of self-obsession—resentment, anger, and fear—and how recovery addresses them.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3112_Triangle-of-Self-Obsession-IP-12-English.pdf" },
    { title: "IP #13: By Young Addicts, For Young Addicts", description: "Written by and for younger members of NA, sharing experience relevant to young people in recovery.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3113_2008-IP-13-English.pdf" },
    { title: "IP #14: One Addict's Experience with Acceptance, Faith, and Commitment", description: "A personal story of working the first three steps of the NA program.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3114_One-Addict-Experience-IP-14-English.pdf" },
    { title: "IP #15: PI and the NA Member", description: "Explains public information service and how NA members can help carry the message to the public.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/en3115-IP-15-English.pdf" },
    { title: "IP #16: For the Newcomer", description: "Provides guidance and encouragement specifically for people new to NA.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3116_For-Newcomer-IP-16-English.pdf" },
    { title: "IP #17: For Those in Treatment", description: "Addresses addicts who are currently in treatment and introduces them to the NA program.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3117-IP-17-English.pdf" },
    { title: "IP #19: Self-Acceptance", description: "Explores the journey of self-acceptance in recovery and learning to love ourselves.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3119_Self-Acceptance-IP-19-English.pdf" },
    { title: "IP #20: H&I Service and the NA Member", description: "Describes Hospitals and Institutions service and how NA members can participate in carrying the message.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3120-IP-20-English.pdf" },
    { title: "IP #21: The Loner: Staying Clean in Isolation", description: "Shares experience for addicts who may be geographically isolated or unable to attend meetings regularly.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3121-IP-21-English.pdf" },
    { title: "IP #23: Staying Clean on the Outside", description: "Written for addicts transitioning from incarceration back to the community and finding recovery through NA.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3123_Staying-Clean-IP-23-English.pdf" },
    { title: "IP #24: Money Matters: Self-Support in NA", description: "Discusses the Seventh Tradition and financial responsibility in NA groups and service.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3124-IP-24-English.pdf" },
    { title: "IP #26: Accessibility for Those with Additional Needs", description: "Addresses making NA meetings and services accessible for members with disabilities and additional needs.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3126-IP-26-English.pdf" },
    { title: "IP #27: For the Parents or Guardians of Young People in NA", description: "Provides information for parents and guardians of young people attending NA meetings.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/EN3127-IP-27-English.pdf" },
    { title: "IP #28: Funding NA Services", description: "Explains how NA services are funded through member contributions and the importance of self-support.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3128_2024-IP-28-English.pdf" },
    { title: "IP #30: Mental Health in Recovery", description: "Reflects the shared experiences of NA members who have found it necessary to seek outside help for mental health concerns.", category: "Informational Pamphlets", externalUrl: "https://na.org/wp-content/uploads/2024/05/3130_MHR-IP-30-English.pdf" },
  ]);

  await db.insert(servicePositions).values([
    { title: "Facilitator", committee: "Admin Committee", cleanTimeRequirement: "2 years", commitmentLength: "1 year", description: "The Facilitator presides over the Group Conscience Meeting with a firm yet understanding hand. They work with the Notestaker to arrange the agenda.", responsibilities: ["Preside over the GCM with a firm yet understanding hand", "Work with Notestaker to arrange the GCM agenda", "May be a cosigner on all bank accounts", "Must be listed as point of contact for group emergencies", "Is prohibited from expressing opinions or presenting ideas on the table", "May NOT vote on Group business except in case of a tie"], additionalNotes: "Requires 1 year prior service as a trusted servant of Another Chance Group.", isFilled: true },
    { title: "Co-Facilitator", committee: "Admin Committee", cleanTimeRequirement: "2 years", commitmentLength: "1 year", description: "The Co-Facilitator assists the Facilitator and presides over meetings in their absence. Responsible for key management and distribution.", responsibilities: ["Preside over the meeting in the absence of the Facilitator", "Responsible for assigning and retrieving front door keys", "Keep accurate records of Key Holders", "Manage Literature Cabinet and Supply Closet keys", "May be a cosigner on all bank accounts", "Must be listed as point of contact for group emergencies"], additionalNotes: "After 1 year as Co-Facilitator, eligible for automatic nomination for Facilitator.", isFilled: true },
    { title: "Notestaker", committee: "Admin Committee", cleanTimeRequirement: "1 year", commitmentLength: "1 year", description: "The Notestaker keeps accurate minutes of all Group Conscience Meetings and manages the meeting agenda.", responsibilities: ["Keep accurate minutes of all GCMs", "Type all ideas, disposition of ideas, elections and announcements", "Post minutes no later than 10 days prior to next GCM", "Post upcoming ideas and announcements 3 weeks prior to GCM", "Must have copies of minutes available at GCM", "Give approved Guideline ideas to Peacekeeper", "Archive full Money Handler reports and notes", "May be a cosigner on all bank accounts"], isFilled: false },
    { title: "Money Handler", committee: "Admin Committee", cleanTimeRequirement: "3 years", commitmentLength: "1 year", description: "The Money Handler manages all financial aspects of the group including bank accounts, contributions, and expenditures.", responsibilities: ["Report monthly contributions and expenditures at every GCM", "Must be a cosigner on all bank accounts", "Keep accurate records of all cash accounts", "Reconcile bank statements", "Open safe and reconcile meeting logs", "Change all login IDs and passwords each term", "Must have proficiency in Excel and Word", "Pay all bills in a timely manner"], additionalNotes: "Must have working knowledge of check writing, bill paying, budgets, and bank reconciliation.", isFilled: true },
    { title: "Assistant Money Handler", committee: "Admin Committee", cleanTimeRequirement: "2 years", commitmentLength: "1 year", description: "Assists and serves as backup for the Money Handler. Cannot reside in same household as Money Handler.", responsibilities: ["Report in absence of Money Handler at GCMs", "Reconcile meeting logs and deposits in Money Handler's absence", "Reconcile individual committee budgets when needed", "May NOT be a cosigner on bank accounts", "Maintain overview of literature and cinderblock logs"], additionalNotes: "After 1 year, eligible for automatic nomination for Money Handler.", isFilled: false },
    { title: "Peacekeeper", committee: "Admin Committee", cleanTimeRequirement: "2 years", commitmentLength: "1 year", description: "The Peacekeeper assists members in properly formatting ideas and serves as parliamentarian for the GCM.", responsibilities: ["Assist members in formatting ideas that change Guidelines", "Act as parliamentarian for the GCM", "Maintain the official copy of Another Chance Group Guidelines", "Hold Guidelines workshops in March and August each year", "Edit Guidelines annually in December", "Must be listed as point of contact for group emergencies", "May be a cosigner on all bank accounts"], isFilled: true },
    { title: "Group Service Representative (GSR)", committee: "Admin Committee", cleanTimeRequirement: "2 years", commitmentLength: "1 year", description: "The GSR speaks for Another Chance Group at the Area, Region, and World levels of NA service.", responsibilities: ["Represent Another Chance Group at Area Service Committee meetings", "Take the Group Conscience opinion to ASC regardless of personal opinion", "Report on Area, Region, and World level activities at monthly GCM", "Attend Regional Assembly once per year", "May be a cosigner on all bank accounts", "Work for the good of NA with neighboring groups"], additionalNotes: "Requires 1 year prior service as a trusted servant of Another Chance Group.", isFilled: true },
    { title: "GSRA (GSR Alternate)", committee: "Admin Committee", cleanTimeRequirement: "1 year", commitmentLength: "2 years", description: "Performs the duties of the GSR in their absence and assists with Area Service Committee attendance.", responsibilities: ["Perform GSR duties in their absence", "Assist GSR in attending Area Service Committee meetings", "Present reports on Area, Region, and World activities when GSR is absent", "Attend Regional Assembly once per year"], additionalNotes: "After 1 year as GSRA, eligible for automatic nomination for GSR. This is a 2-year commitment.", isFilled: false },
    { title: "Activities Facilitator", committee: "Group Committees", cleanTimeRequirement: "1 year", commitmentLength: "1 year", description: "Plans, organizes, and promotes all activities for the Group including birthday celebrations, game nights, and workshops.", responsibilities: ["Plan, organize and promote all group activities", "Coordinate with GSR to avoid scheduling conflicts with other groups", "Maintain contact with Area Activities representatives", "Attend Area Activities meetings when possible"], isFilled: false },
    { title: "Cleanup Facilitator", committee: "Group Committees", cleanTimeRequirement: "90 days", commitmentLength: "6 months", description: "Brings unity to the Group by coordinating members to maintain a clean meeting environment.", responsibilities: ["Plan and coordinate cleanup days", "Inform Program Facilitator of cleanup dates and times", "Maintain inventory of cleaning supplies", "Solicit members for basic meeting-by-meeting cleaning", "Coordinate taking out trash, wiping down meeting room, and cleaning bathrooms"], isFilled: false },
    { title: "Cinderblock Facilitator", committee: "Group Committees", cleanTimeRequirement: "90 days", commitmentLength: "6 months", description: "Manages the cinderblock wall where members' names and clean dates are displayed.", responsibilities: ["Keep accurate records of cinderblock renewals", "Oversee painting of blocks and report to Group Conscience monthly", "Manage $5 annual renewal contributions", "Handle 'In Memory Of' blocks according to guidelines", "Manage block removals for non-renewal or relapse"], isFilled: true },
    { title: "Maintenance Facilitator", committee: "Group Committees", cleanTimeRequirement: "6 months", commitmentLength: "6 months", description: "Responsible for the building maintenance and upkeep of the group's facility.", responsibilities: ["Keep group informed of code changes and implementation", "Establish minimum standards of cleanliness, safety, and appearance", "Coordinate HVAC, plumbing, electrical, and structural upkeep", "Manage sanitation, floors, furniture, and filters", "Act as special worker when dealing with outside officials"], isFilled: false },
    { title: "Vendor Facilitator", committee: "Group Committees", cleanTimeRequirement: "1 year", commitmentLength: "1 year", description: "Maintains and ensures that all consumable supplies are available for the group.", responsibilities: ["Stock and maintain inventory control of supplies", "Manage coffee, cups, creamer, sugar, filters, envelopes, soap, paper goods, etc.", "Submit budget to Finance Facilitator at November GCM"], isFilled: true },
    { title: "Phone List Facilitator", committee: "Group Committees", cleanTimeRequirement: "90 days", commitmentLength: "6 months", description: "Carries the message by providing updated phone numbers for members at all times.", responsibilities: ["Update and revise phone list every 3 months", "Post list on bulletin board for changes", "Maintain sufficient copies of updated phone lists at the group"], isFilled: false },
    { title: "Program Facilitator", committee: "Group Committees", cleanTimeRequirement: "1 year", commitmentLength: "6 months", description: "Oversees all aspects of Another Chance's program service structure including meetings and speakers.", responsibilities: ["Maintain focus on concerns affecting the group's ability to fulfill primary purpose", "Invite and seek out keynote speakers", "Encourage members to attend Chairperson's Workshop", "Conduct monthly Chairperson's Workshop", "Work with Committee Facilitators to schedule workshops", "Ensure Chairperson board and calendar are updated monthly"], isFilled: true },
    { title: "Program Co-Facilitator", committee: "Group Committees", cleanTimeRequirement: "6 months", commitmentLength: "6 months", description: "Assists the Program Facilitator with all concerns and responsibilities of the position.", responsibilities: ["Assist Program Facilitator with encouraging members to chair meetings", "Keep Program Facilitator apprised of any concerns", "Help with meeting format concerns and building/supply access"], additionalNotes: "May transition to 1-year commitment as Program Facilitator pending elections.", isFilled: false },
    { title: "Finance Facilitator", committee: "Group Committees", cleanTimeRequirement: "1 year", commitmentLength: "1 year", description: "Oversees the financial planning and budgeting process for the group.", responsibilities: ["Establish method for determining Area, Region, and World contributions", "Submit contribution methods as ideas for GCM approval", "Audit Money Handler fees and report findings quarterly", "Review and manage group and committee budgets"], isFilled: true },
    { title: "Literature Facilitator", committee: "Group Committees", cleanTimeRequirement: "1 year", commitmentLength: "6 months", description: "Manages the group's NA literature inventory and sales.", responsibilities: ["Maintain adequate stock of NA literature", "Handle literature sales and inventory tracking", "Order new literature as needed", "Report on literature activity at GCM"], isFilled: false },
    { title: "Anniversary Facilitator", committee: "Group Committees", cleanTimeRequirement: "1 year", commitmentLength: "1 year", description: "Coordinates celebration of members' recovery anniversaries and milestones.", responsibilities: ["Organize monthly birthday/anniversary celebrations", "Coordinate with Activities Facilitator for special events", "Track member anniversary dates", "Order key tags and medallions for celebrations"], isFilled: false },
    { title: "Meeting Chairperson", committee: "Meeting Support", cleanTimeRequirement: "60 days", commitmentLength: "1 month", description: "Chairs individual NA meetings, leading the format and facilitating sharing.", responsibilities: ["Open and close meetings following the established format", "Select topics or readings for the meeting", "Facilitate orderly sharing among attendees", "Ensure meeting stays on track and within time limits"], isFilled: false },
    { title: "Key Holder", committee: "Meeting Support", cleanTimeRequirement: "1 year (suggested)", commitmentLength: "6 months", description: "Trusted members who hold keys to the group's facility for opening and closing meetings.", responsibilities: ["Open the facility before scheduled meetings", "Ensure facility is properly secured after meetings", "Return keys to Co-Facilitator when commitment ends", "Maintain confidentiality of key holder information"], additionalNotes: "Exceptions to the 1-year clean time suggestion may be made.", isFilled: false },
    { title: "Help Line Representative", committee: "Group Representatives", cleanTimeRequirement: "90 days", commitmentLength: "6 months", description: "Represents Another Chance Group on the Area Help Line committee.", responsibilities: ["Attend Area Help Line committee meetings", "Report Help Line activities at GCM", "Coordinate help line volunteer opportunities for group members"], isFilled: false },
    { title: "H&I Representative", committee: "Group Representatives", cleanTimeRequirement: "90 days", commitmentLength: "6 months", description: "Represents Another Chance Group on the Area Hospitals & Institutions committee.", responsibilities: ["Attend Area H&I committee meetings", "Report H&I activities at GCM", "Coordinate H&I volunteer opportunities for group members", "Help carry the message to addicts in institutions"], isFilled: false },
    { title: "Public Information Representative", committee: "Group Representatives", cleanTimeRequirement: "90 days", commitmentLength: "6 months", description: "Represents Another Chance Group on the Area Public Information committee.", responsibilities: ["Attend Area PI committee meetings", "Report PI activities at GCM", "Help carry the message through public information channels"], isFilled: false },
    { title: "Web Servant", committee: "Group Representatives", cleanTimeRequirement: "90 days", commitmentLength: "6 months", description: "Manages the group's online presence and digital communications.", responsibilities: ["Maintain group website and online information", "Update meeting schedules and events online", "Coordinate with Area web servant", "Report web activities at GCM"], isFilled: false },
  ]);

  console.log("Database seeded successfully");
}
